// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do one of these:
//
//    using mvsep_cli;
//
//    var mvsepStatus = MvsepStatus.FromJson(jsonString);
//    var mvsepUploadSuccess = MvsepUploadSuccess.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace mvsep_cli
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class MvsepStatus
    {
        [JsonPropertyName("success")]
        public bool Success { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }

        [JsonPropertyName("data")]
        public MvsepStatusData Data { get; set; }
    }

    public partial class MvsepStatusData
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("message")]
        public string Message { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("hash")]
        public string Hash { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("algorithm")]
        public string Algorithm { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("algorithm_description")]
        public string AlgorithmDescription { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("output_format")]
        public string OutputFormat { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("tags")]
        public DataTags Tags { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("input_file")]
        public File InputFile { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("files")]
        public File[] Files { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("date")]
        [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
        public DateTimeOffset? Date { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("transcription")]
        public object[] Transcription { get; set; }
    }

    public partial class File
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("url")]
        public Uri Url { get; set; }

        [JsonPropertyName("size")]
        public string Size { get; set; }

        [JsonPropertyName("image")]
        public object Image { get; set; }

        [JsonPropertyName("download")]
        public string Download { get; set; }
    }

    public partial class DataTags
    {
        [JsonPropertyName("audio")]
        public Audio Audio { get; set; }

        [JsonPropertyName("tags")]
        public TagsTags Tags { get; set; }
    }

    public partial class Audio
    {
        [JsonPropertyName("dataformat")]
        public string Dataformat { get; set; }

        [JsonPropertyName("bitrate_mode")]
        public string BitrateMode { get; set; }

        [JsonPropertyName("lossless")]
        public bool Lossless { get; set; }

        [JsonPropertyName("sample_rate")]
        public long SampleRate { get; set; }

        [JsonPropertyName("channels")]
        public long Channels { get; set; }

        [JsonPropertyName("bits_per_sample")]
        public long BitsPerSample { get; set; }

        [JsonPropertyName("bitrate")]
        public double Bitrate { get; set; }

        [JsonPropertyName("encoder")]
        public string Encoder { get; set; }

        [JsonPropertyName("channelmode")]
        public string Channelmode { get; set; }

        [JsonPropertyName("compression_ratio")]
        public double CompressionRatio { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("streams")]
        public Audio[] Streams { get; set; }
    }

    public partial class TagsTags
    {
        [JsonPropertyName("vorbiscomment")]
        public Vorbiscomment Vorbiscomment { get; set; }
    }

    public partial class Vorbiscomment
    {
        [JsonPropertyName("encoder")]
        public string[] Encoder { get; set; }
    }

    public partial class MvsepUploadSuccess
    {
        [JsonPropertyName("success")]
        public bool Success { get; set; }

        [JsonPropertyName("data")]
        public MvsepUploadSuccessData Data { get; set; }
    }

    public partial class MvsepUploadSuccessData
    {
        [JsonPropertyName("link")]
        public Uri Link { get; set; }

        [JsonPropertyName("hash")]
        public string Hash { get; set; }
    }

    public partial class MvsepStatus
    {
        public static MvsepStatus FromJson(string json) =>
 JsonSerializer.Deserialize(json, MvsepJsonContext.Default.MvsepStatus)!;
 }

 public partial class MvsepUploadSuccess
 {
 public static MvsepUploadSuccess FromJson(string json) =>
 JsonSerializer.Deserialize(json, MvsepJsonContext.Default.MvsepUploadSuccess)!;
 }

 public static class Serialize
 {
 public static string ToJson(this MvsepStatus self) =>
 JsonSerializer.Serialize(self, MvsepJsonContext.Default.MvsepStatus);
 public static string ToJson(this MvsepUploadSuccess self) =>
 JsonSerializer.Serialize(self, MvsepJsonContext.Default.MvsepUploadSuccess);
 }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
            get => _dateTimeStyles;
            set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
            get => _dateTimeFormat ?? string.Empty;
            set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
            get => _culture ?? CultureInfo.CurrentCulture;
            set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
            string text;


            if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                    || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
            {
                value = value.ToUniversalTime();
            }

            text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

            writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? dateText = reader.GetString();

            if (string.IsNullOrEmpty(dateText) == false)
            {
                if (!string.IsNullOrEmpty(_dateTimeFormat))
                {
                    return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                }
                else
                {
                    return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                }
            }
            else
            {
                return default(DateTimeOffset);
            }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }

    // AOT-friendly converter for DateTimeOffset?
 public class NullableDateTimeOffsetConverter : JsonConverter<DateTimeOffset?>
 {
 public override DateTimeOffset? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
 {
 if (reader.TokenType == JsonTokenType.Null)
 return null;
 if (reader.TokenType == JsonTokenType.String)
 {
 var str = reader.GetString();
 if (string.IsNullOrWhiteSpace(str))
 return null;
 if (DateTimeOffset.TryParse(str, out var dto))
 return dto;
 }
 return null;
 }
 public override void Write(Utf8JsonWriter writer, DateTimeOffset? value, JsonSerializerOptions options)
 {
 if (value.HasValue)
 writer.WriteStringValue(value.Value);
 else
 writer.WriteNullValue();
 }
 }

    [JsonSerializable(typeof(MvsepStatus))]
    [JsonSerializable(typeof(MvsepUploadSuccess))]
    public partial class MvsepJsonContext : JsonSerializerContext;
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
